package org.hectordam.beans;

// Generated 03-feb-2014 23:09:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Armas generated by hbm2java
 */
@Entity
@Table(name = "armas", catalog = "juegohibernate")
public class Armas implements java.io.Serializable {

	private Integer id;
	private Personajes personajes;
	private String nombre;
	private String descripcion;
	private Integer ataque;

	public Armas() {
	}

	public Armas(Personajes personajes) {
		this.personajes = personajes;
	}

	public Armas(Personajes personajes, String nombre, String descripcion,
			Integer ataque) {
		this.personajes = personajes;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.ataque = ataque;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personaje", nullable = false)
	public Personajes getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Personajes personajes) {
		this.personajes = personajes;
	}

	@Column(name = "nombre", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ataque")
	public Integer getAtaque() {
		return this.ataque;
	}

	public void setAtaque(Integer ataque) {
		this.ataque = ataque;
	}

}
