package org.hectordam.beans;

// Generated 03-feb-2014 23:09:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "juegohibernate")
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String poblacion;
	private String correo;
	private String nombre;
	private String telefono;
	private Set<Personajes> personajeses = new HashSet<Personajes>(0);
	private Set<Mapas> mapases = new HashSet<Mapas>(0);
	private Set<Misiones> misioneses = new HashSet<Misiones>(0);

	public Usuarios() {
	}

	public Usuarios(String poblacion, String correo, String nombre,
			String telefono, Set<Personajes> personajeses, Set<Mapas> mapases,
			Set<Misiones> misioneses) {
		this.poblacion = poblacion;
		this.correo = correo;
		this.nombre = nombre;
		this.telefono = telefono;
		this.personajeses = personajeses;
		this.mapases = mapases;
		this.misioneses = misioneses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "poblacion", length = 20)
	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	@Column(name = "correo", length = 30)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "nombre", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<Personajes> getPersonajeses() {
		return this.personajeses;
	}

	public void setPersonajeses(Set<Personajes> personajeses) {
		this.personajeses = personajeses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuarios_mapas", catalog = "juegohibernate", joinColumns = { @JoinColumn(name = "id_usuario", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_mapa", nullable = false, updatable = false) })
	public Set<Mapas> getMapases() {
		return this.mapases;
	}

	public void setMapases(Set<Mapas> mapases) {
		this.mapases = mapases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<Misiones> getMisioneses() {
		return this.misioneses;
	}

	public void setMisioneses(Set<Misiones> misioneses) {
		this.misioneses = misioneses;
	}

}
